// Canonical option lists for Field Exceptions and Document Holds.
// Used by:
//   - the list-search picker on the Search page (multi-select dropdowns)
//   - the Results grid pill columns

export const FIELD_EXCEPTION_OPTIONS: string[] = [
  'Bill To Address1',
  'Bill To City',
  'Bill To Full Address',
  'Bill To Name',
  'Bill To State',
  'Bill To Zip Code',
  'Broker Load Number',
  'Carrier Address1',
  'Carrier City',
  'Carrier Full Address',
  'Carrier Name',
  'Carrier State',
  'Carrier Zip Code',
  'Consignee Address1',
  'Consignee City',
  'Consignee Full Address',
  'Consignee Name',
  'Consignee State',
  'Consignee Zip Code',
  'Currency',
  'Delivery Date',
  'Destination Address1',
  'Destination City',
  'Destination Full Address',
  'Destination Name',
  'Destination State',
  'Destination Zip Code',
  'Factor Name',
  'Factor Remit To Address1',
  'Factor Remit To City',
  'Factor Remit To Full Address',
  'Factor Remit To State',
  'Factor Remit To Zip Code',
  'Invoice Amount',
  'Invoice Date',
  'Invoice Number',
  'Origin Address1',
  'Origin City',
  'Origin Full Address',
  'Origin Name',
  'Origin State',
  'Origin Zip Code',
  'Remit To Address1',
  'Remit To City',
  'Remit To Full Address',
  'Remit To Name',
  'Remit To State',
  'Remit To Zip Code',
  'Ship Date',
  'Shipper Address1',
  'Shipper City',
  'Shipper Full Address',
  'Shipper Name',
  'Shipper State',
  'Shipper Zip Code',
];

export const DOCUMENT_HOLD_OPTIONS: string[] = [
  'BOL Hold',
  'Carrier Not Regulated',
  'charlie test',
  'Field Errors Not Resolved',
  'Fields Error!',
  'hold reason',
  'Missing Documents!',
];
